services:
  postgres:
    image: postgres:16
    container_name: portfolio_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: 8082
      JWT_SECRET: ${JWT_SECRET}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      VALID_API_LOGIN: ${VALID_API_LOGIN}
      VALID_API_PASSWORD: ${VALID_API_PASSWORD}
      INVALID_API_LOGIN: ${INVALID_API_LOGIN}
      INVALID_API_PASSWORD: ${INVALID_API_PASSWORD}
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  pgdata: