version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: portfolio_postgres
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: portfolio_pass
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  pgdata: